### ISSUE TITLE
Add a 'publish' field to the source fields sheet

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/field-level-mapping-template#13]
According to the [mapping gudiance](https://standard.open-contracting.org/latest/en/guidance/map/#splitting-up-the-work):

> The preferred approach is to eventually list all the data elements within your data sources in your Field-Level Mapping, decide whether to publish each, and then map each. 

We should add a field to the source fields sheet so publishers can indicate whether they plan to publish each field, this will help analysts avoid spending time advising on mapping fields that are not planned for publication.

**Comment by odscjen** [comment]
fixed in updated version 0.91 published 20220407
