### ISSUE TITLE
Difference between mapping template in Spanish and English 

### ISSUE THREAD

**Issue by cecicasco** [open-contracting/field-level-mapping-template#20]
Hi! 
I was looking at the last mapping template and I found some differences between then, for example in the page "(OCDS) 1. General (todas las etapas)" of [[ES] OCDS - Field Level Mapping Template for OCDS 1.1 (Template Version 0.9) #public](https://docs.google.com/spreadsheets/d/1O1YUDqT-gXmVc96YlCK16YbTmLzOdg2whGL1RtHytm0/edit#gid=1843378791) there are not mention of the field _contracts/implementation/transactions/payer_ as it is in the [OCDS - Field Level Mapping Template for OCDS 1.1 (Template Version 0.9) #public](https://docs.google.com/spreadsheets/d/1tDv3vpN9wbcpY6MagIFEUksJAiKeddnwnfNWGXKAQRs/edit?pli=1#gid=1756932601)

what we should do in this case?

**Comment by jpmckinney** [comment]
Please add the missing field to the Spanish template.

cc @yolile

**Comment by cecicasco** [comment]
so, can I edit it manually?

**Comment by jpmckinney** [comment]
Yes
