### ISSUE TITLE
Provide glossary and/or clarify that description fields are generated from the schema

### ISSUE THREAD

**Issue by pindec** [open-contracting/field-level-mapping-template#21]
Feedback from a publisher suggested adding a glossary to avoid misinterpretation of terminology by non-English speakers.

This suggests it's not clear that the "description" fields are drawn from the schema itself. We should clarify this in the "Field Level Mapping Overview" tab and in the [Mapping Template Guidance](https://www.open-contracting.org/resources/ocds-1-1-mapping-template-guidance/).

**Comment by odscjen** [comment]
fixed in updated version 0.91 published 20220407
