### ISSUE TITLE
Remove the "Mapped" column from the "Source Fields" sheet

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/field-level-mapping-template#5]
Originally reported in CRM-5537 by @duncandewhurst

> The "Mapping details" column makes it redundant.

**Comment by duncandewhurst** [comment]
I remember why there are two columns now: the formulae used in 'Mapping details' aren't compatible with MS Excel or Libre/Open Office so the 'Mapped' column serves as a proxy for users of those tools.

I can't find a method of generating the 'Mapping details' column that is compatible with both Google Sheets and other spreadsheet tools.

The `FILTER` formula is compatible with recent (Microsoft 365) versions of Excel, but Google Sheets replaces the formula when exporting to .xlsx.

I think the best option is to keep both columns. The alternative would be to maintain two versions of the template, with the Excel version using VBA. However that would not be compatible with other spreadsheet tools and there would likely be issues with security warnings etc. related to 3rd party macros, so I don't think it's worth the effort.
