### ISSUE TITLE
Visual improvements

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/field-level-mapping-template#6]
* [x] Format the schema and codelists sheets so that they are more user friendly (use word-wrap etc.)

First bullet originally reported in CRM-5537 by @duncandewhurst

**Comment by duncandewhurst** [comment]
Done in the latest version, but I can't seem to check the checkbox or close the issue. @jpmckinney please could you check the permissions on this repo? Thanks!

**Comment by jpmckinney** [comment]
@duncandewhurst Should be fixed now.

Also, @romifz, you should be able to push to the repo now.

**Comment by duncandewhurst** [comment]
Thanks!
